# This workflow will do a clean install of node dependencies, and run the linter and tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  # Any additional branches here will currently be treated as release (or maintenance) branches.
  # if the need to run jobs on other branches emerges, then the release job will need a better
  # condition expression.
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test:
    # https://github.community/t/github-actions-does-not-respect-skip-ci/17325/9
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
        with:
          # For commitlint; ideally this would only check out the feature branch's history, but
          # that's not currently an option.
          fetch-depth: ${{ github.event_name == 'push' }}
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        if: '!steps.cache.outputs.cache-hit'
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        if: '!steps.cache.outputs.cache-hit'
        run: yarn install --immutable
      - run: yarn ci
        env:
          BEE_QUEUE_TEST_REDIS: redis://localhost:6379
